__Import Numpy__

In [61]:
import numpy as np

__Create an array of 10 zeroes__

In [62]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

__Create an array of 10 ones__

In [63]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

__Create an array of 10 fives__

In [64]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

__Create an array of integers from 10-50__

In [65]:
np.array(np.arange(10,51))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

__Create an array of even int from 10-50__

In [66]:
np.array(np.arange(0,51,2))

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

__Create a 3x3 matrix with values from 0-8__

In [67]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

__Generate a random number between 0-1__

In [68]:
np.random.rand(1)

array([0.36409843])

__Create a matrix using the code given:__

In [69]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

__Find sum of values in mat__

In [70]:
np.sum(mat)

325

__Find std dev of values in mat__

In [71]:
np.std(mat)

7.211102550927978

__Create a matrix of ones named mat1__

In [72]:
mat1 = np.ones(25).reshape(5,5)

__Add values of mat to those of mat1__

In [73]:
mat + mat1

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21.],
       [22., 23., 24., 25., 26.]])

__Multiply values of mat by those of mat1__

In [74]:
mat * mat1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])